export interface Book {
  id: number;
  title: string;
  author: string;
  published_date: string;
  genre: string;
  is_borrowed: boolean;
  num_of_holds: number;
  num_of_copies: number;
  book_cover: string;
}

export const books: Book[] = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    published_date: "1960-07-11",
    genre: "Fiction",
    is_borrowed: true,
    num_of_holds: 3,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    published_date: "1949-06-08",
    genre: "Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 5,
    book_cover: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
  },
  {
    id: 3,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    published_date: "1813-01-28",
    genre: "Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
  },
  {
    id: 4,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    published_date: "1951-07-16",
    genre: "Fiction",
    is_borrowed: true,
    num_of_holds: 2,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/8231856-L.jpg",
  },
  {
    id: 5,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    published_date: "1925-04-10",
    genre: "Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 6,
    book_cover: "https://covers.openlibrary.org/b/id/7222276-L.jpg",
  },
  {
    id: 6,
    title: "Brave New World",
    author: "Aldous Huxley",
    published_date: "1932-08-18",
    genre: "Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/8775362-L.jpg",
  },
  {
    id: 7,
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    published_date: "1847-10-16",
    genre: "Fiction",
    is_borrowed: true,
    num_of_holds: 0,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/8231990-L.jpg",
  },
  {
    id: 8,
    title: "Wuthering Heights",
    author: "Emily Brontë",
    published_date: "1847-12-01",
    genre: "Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/8231859-L.jpg",
  },
  {
    id: 9,
    title: "Animal Farm",
    author: "George Orwell",
    published_date: "1945-08-17",
    genre: "Fiction",
    is_borrowed: true,
    num_of_holds: 5,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/11153701-L.jpg",
  },
  {
    id: 10,
    title: "Little Women",
    author: "Louisa May Alcott",
    published_date: "1868-09-30",
    genre: "Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/8225631-L.jpg",
  },

  {
    id: 11,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    published_date: "1937-09-21",
    genre: "Fantasy",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 5,
    book_cover: "https://covers.openlibrary.org/b/id/6979861-L.jpg",
  },
  {
    id: 12,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    published_date: "1997-06-26",
    genre: "Fantasy",
    is_borrowed: true,
    num_of_holds: 4,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/7984916-L.jpg",
  },
  {
    id: 13,
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    published_date: "2007-03-27",
    genre: "Fantasy",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/8104467-L.jpg",
  },
  {
    id: 14,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    published_date: "1996-08-06",
    genre: "Fantasy",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 6,
    book_cover: "https://covers.openlibrary.org/b/id/7292161-L.jpg",
  },
  {
    id: 15,
    title: "Mistborn: The Final Empire",
    author: "Brandon Sanderson",
    published_date: "2006-07-17",
    genre: "Fantasy",
    is_borrowed: true,
    num_of_holds: 0,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/6786973-L.jpg",
  },
  {
    id: 16,
    title: "The Fellowship of the Ring",
    author: "J.R.R. Tolkien",
    published_date: "1954-07-29",
    genre: "Fantasy",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 7,
    book_cover: "https://covers.openlibrary.org/b/id/8231852-L.jpg",
  },
  {
    id: 17,
    title: "The Lion, the Witch and the Wardrobe",
    author: "C.S. Lewis",
    published_date: "1950-10-16",
    genre: "Fantasy",
    is_borrowed: true,
    num_of_holds: 2,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/8228690-L.jpg",
  },
  {
    id: 18,
    title: "The Lies of Locke Lamora",
    author: "Scott Lynch",
    published_date: "2006-06-27",
    genre: "Fantasy",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/8208085-L.jpg",
  },
  {
    id: 19,
    title: "Eragon",
    author: "Christopher Paolini",
    published_date: "2002-08-26",
    genre: "Fantasy",
    is_borrowed: true,
    num_of_holds: 1,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/8139342-L.jpg",
  },
  {
    id: 20,
    title: "American Gods",
    author: "Neil Gaiman",
    published_date: "2001-06-19",
    genre: "Fantasy",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/8101344-L.jpg",
  },
  {
    id: 21,
    title: "Gone Girl",
    author: "Gillian Flynn",
    published_date: "2012-06-05",
    genre: "Mystery",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/8225572-L.jpg",
  },
  {
    id: 22,
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    published_date: "2005-08-01",
    genre: "Mystery",
    is_borrowed: true,
    num_of_holds: 2,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/6660731-L.jpg",
  },
  {
    id: 23,
    title: "The Da Vinci Code",
    author: "Dan Brown",
    published_date: "2003-03-18",
    genre: "Mystery",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/295415-L.jpg",
  },
  {
    id: 24,
    title: "Big Little Lies",
    author: "Liane Moriarty",
    published_date: "2014-07-29",
    genre: "Mystery",
    is_borrowed: true,
    num_of_holds: 0,
    num_of_copies: 5,
    book_cover: "https://covers.openlibrary.org/b/id/8225635-L.jpg",
  },
  {
    id: 25,
    title: "And Then There Were None",
    author: "Agatha Christie",
    published_date: "1939-11-06",
    genre: "Mystery",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/8235264-L.jpg",
  },
  {
    id: 26,
    title: "The Hound of the Baskervilles",
    author: "Arthur Conan Doyle",
    published_date: "1902-04-01",
    genre: "Mystery",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 6,
    book_cover: "https://covers.openlibrary.org/b/id/8235226-L.jpg",
  },
  {
    id: 27,
    title: "In the Woods",
    author: "Tana French",
    published_date: "2007-05-17",
    genre: "Mystery",
    is_borrowed: true,
    num_of_holds: 2,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/8234562-L.jpg",
  },
  {
    id: 28,
    title: "The Cuckoo's Calling",
    author: "Robert Galbraith (J.K. Rowling)",
    published_date: "2013-04-18",
    genre: "Mystery",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/8232009-L.jpg",
  },
  {
    id: 29,
    title: "Sharp Objects",
    author: "Gillian Flynn",
    published_date: "2006-09-26",
    genre: "Mystery",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 5,
    book_cover: "https://covers.openlibrary.org/b/id/8225634-L.jpg",
  },
  {
    id: 30,
    title: "The Silent Patient",
    author: "Alex Michaelides",
    published_date: "2019-02-05",
    genre: "Mystery",
    is_borrowed: true,
    num_of_holds: 3,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/9252274-L.jpg",
  },
  {
    id: 31,
    title: "Dune",
    author: "Frank Herbert",
    published_date: "1965-08-01",
    genre: "Science Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/8101341-L.jpg",
  },
  {
    id: 32,
    title: "Ender's Game",
    author: "Orson Scott Card",
    published_date: "1985-01-15",
    genre: "Science Fiction",
    is_borrowed: true,
    num_of_holds: 2,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/7669258-L.jpg",
  },
  {
    id: 33,
    title: "Neuromancer",
    author: "William Gibson",
    published_date: "1984-07-01",
    genre: "Science Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 5,
    book_cover: "https://covers.openlibrary.org/b/id/8163691-L.jpg",
  },
  {
    id: 34,
    title: "Foundation",
    author: "Isaac Asimov",
    published_date: "1951-05-01",
    genre: "Science Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/6979864-L.jpg",
  },
  {
    id: 35,
    title: "The Martian",
    author: "Andy Weir",
    published_date: "2011-09-27",
    genre: "Science Fiction",
    is_borrowed: true,
    num_of_holds: 1,
    num_of_copies: 6,
    book_cover: "https://covers.openlibrary.org/b/id/8165587-L.jpg",
  },
  {
    id: 36,
    title: "Do Androids Dream of Electric Sheep?",
    author: "Philip K. Dick",
    published_date: "1968-03-01",
    genre: "Science Fiction",
    is_borrowed: true,
    num_of_holds: 2,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/8231932-L.jpg",
  },
  {
    id: 37,
    title: "Snow Crash",
    author: "Neal Stephenson",
    published_date: "1992-06-01",
    genre: "Science Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/8150616-L.jpg",
  },
  {
    id: 38,
    title: "The Left Hand of Darkness",
    author: "Ursula K. Le Guin",
    published_date: "1969-03-01",
    genre: "Science Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/8281661-L.jpg",
  },
  {
    id: 39,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    published_date: "2008-09-14",
    genre: "Science Fiction",
    is_borrowed: true,
    num_of_holds: 4,
    num_of_copies: 5,
    book_cover: "https://covers.openlibrary.org/b/id/7840716-L.jpg",
  },
  {
    id: 40,
    title: "Ready Player One",
    author: "Ernest Cline",
    published_date: "2011-08-16",
    genre: "Science Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/8231853-L.jpg",
  },
  {
    id: 41,
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    published_date: "2011-01-01",
    genre: "Non-Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 5,
    book_cover: "https://covers.openlibrary.org/b/id/8370226-L.jpg",
  },
  {
    id: 42,
    title: "Educated",
    author: "Tara Westover",
    published_date: "2018-02-20",
    genre: "Non-Fiction",
    is_borrowed: true,
    num_of_holds: 2,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/8369256-L.jpg",
  },
  {
    id: 43,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    published_date: "2011-10-25",
    genre: "Non-Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/7171623-L.jpg",
  },
  {
    id: 44,
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    published_date: "2010-02-02",
    genre: "Non-Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/7254770-L.jpg",
  },
  {
    id: 45,
    title: "The Wright Brothers",
    author: "David McCullough",
    published_date: "2015-05-05",
    genre: "Non-Fiction",
    is_borrowed: true,
    num_of_holds: 3,
    num_of_copies: 6,
    book_cover: "https://covers.openlibrary.org/b/id/8588736-L.jpg",
  },
  {
    id: 46,
    title: "Quiet: The Power of Introverts in a World That Can't Stop Talking",
    author: "Susan Cain",
    published_date: "2012-01-24",
    genre: "Non-Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/7574333-L.jpg",
  },
  {
    id: 47,
    title: "Freakonomics",
    author: "Steven D. Levitt & Stephen J. Dubner",
    published_date: "2005-04-12",
    genre: "Non-Fiction",
    is_borrowed: true,
    num_of_holds: 1,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/7222278-L.jpg",
  },
  {
    id: 48,
    title: "Bad Blood: Secrets and Lies in a Silicon Valley Startup",
    author: "John Carreyrou",
    published_date: "2018-05-21",
    genre: "Non-Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 5,
    book_cover: "https://covers.openlibrary.org/b/id/8770641-L.jpg",
  },
  {
    id: 49,
    title: "The Power of Habit",
    author: "Charles Duhigg",
    published_date: "2012-02-28",
    genre: "Non-Fiction",
    is_borrowed: true,
    num_of_holds: 0,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/7357460-L.jpg",
  },
  {
    id: 50,
    title: "Into the Wild",
    author: "Jon Krakauer",
    published_date: "1996-01-13",
    genre: "Non-Fiction",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/8228694-L.jpg",
  },
  {
    id: 51,
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    published_date: "1947-06-25",
    genre: "Biography",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/7109021-L.jpg",
  },
  {
    id: 52,
    title: "Steve Jobs",
    author: "Walter Isaacson",
    published_date: "2011-10-24",
    genre: "Biography",
    is_borrowed: true,
    num_of_holds: 3,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/7275320-L.jpg",
  },
  {
    id: 53,
    title: "Becoming",
    author: "Michelle Obama",
    published_date: "2018-11-13",
    genre: "Biography",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/8878288-L.jpg",
  },
  {
    id: 54,
    title: "Alexander Hamilton",
    author: "Ron Chernow",
    published_date: "2004-04-26",
    genre: "Biography",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 5,
    book_cover: "https://covers.openlibrary.org/b/id/7675329-L.jpg",
  },
  {
    id: 55,
    title: "Long Walk to Freedom",
    author: "Nelson Mandela",
    published_date: "1994-11-12",
    genre: "Biography",
    is_borrowed: true,
    num_of_holds: 2,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/7305231-L.jpg",
  },
  {
    id: 56,
    title: "Einstein: His Life and Universe",
    author: "Walter Isaacson",
    published_date: "2007-04-10",
    genre: "Biography",
    is_borrowed: true,
    num_of_holds: 1,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/7300829-L.jpg",
  },
  {
    id: 57,
    title: "Wild Swans: Three Daughters of China",
    author: "Jung Chang",
    published_date: "1991-05-16",
    genre: "Biography",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/8091372-L.jpg",
  },
  {
    id: 58,
    title: "The Glass Castle",
    author: "Jeanette Walls",
    published_date: "2005-03-01",
    genre: "Biography",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/8231505-L.jpg",
  },
  {
    id: 59,
    title: "Bossypants",
    author: "Tina Fey",
    published_date: "2011-04-05",
    genre: "Biography",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 5,
    book_cover: "https://covers.openlibrary.org/b/id/7275310-L.jpg",
  },
  {
    id: 60,
    title: "I Am Malala",
    author: "Malala Yousafzai",
    published_date: "2013-10-08",
    genre: "Biography",
    is_borrowed: true,
    num_of_holds: 3,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/8231884-L.jpg",
  },
  {
    id: 61,
    title: "Educating",
    author: "Tara Westover",
    published_date: "2018-02-18",
    genre: "Biography",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/8994800-L.jpg",
  },
  {
    id: 62,
    title: "All the Light We Cannot See",
    author: "Anthony Doerr",
    published_date: "2014-05-06",
    genre: "Historical",
    is_borrowed: true,
    num_of_holds: 1,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/8228690-L.jpg",
  },
  {
    id: 63,
    title: "The Book Thief",
    author: "Markus Zusak",
    published_date: "2005-03-14",
    genre: "Historical",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/8235781-L.jpg",
  },
  {
    id: 64,
    title: "The Pillars of the Earth",
    author: "Ken Follett",
    published_date: "1989-09-01",
    genre: "Historical",
    is_borrowed: true,
    num_of_holds: 0,
    num_of_copies: 2,
    book_cover: "https://covers.openlibrary.org/b/id/7944916-L.jpg",
  },
  {
    id: 65,
    title: "War and Peace",
    author: "Leo Tolstoy",
    published_date: "1869-01-01",
    genre: "Historical",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/8231851-L.jpg",
  },
  {
    id: 66,
    title: "The Nightingale",
    author: "Kristin Hannah",
    published_date: "2015-02-03",
    genre: "Historical",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 5,
    book_cover: "https://covers.openlibrary.org/b/id/8325466-L.jpg",
  },
  {
    id: 67,
    title: "The Other Boleyn Girl",
    author: "Philippa Gregory",
    published_date: "2001-05-21",
    genre: "Historical",
    is_borrowed: true,
    num_of_holds: 3,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/240726-L.jpg",
  },
  {
    id: 68,
    title: "Wolf Hall",
    author: "Hilary Mantel",
    published_date: "2009-04-30",
    genre: "Historical",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/7107745-L.jpg",
  },
  {
    id: 69,
    title: "The Help",
    author: "Kathryn Stockett",
    published_date: "2009-02-10",
    genre: "Historical",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 3,
    book_cover: "https://covers.openlibrary.org/b/id/8222243-L.jpg",
  },
  {
    id: 70,
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    published_date: "1859-04-30",
    genre: "Historical",
    is_borrowed: true,
    num_of_holds: 2,
    num_of_copies: 5,
    book_cover: "https://covers.openlibrary.org/b/id/8225636-L.jpg",
  },
  {
    id: 71,
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    published_date: "2003-05-29",
    genre: "Historical",
    is_borrowed: false,
    num_of_holds: 0,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/5182392-L.jpg",
  },
  {
    id: 72,
    title: "Memoirs of a Geisha",
    author: "Arthur Golden",
    published_date: "1997-09-27",
    genre: "Historical",
    is_borrowed: true,
    num_of_holds: 3,
    num_of_copies: 4,
    book_cover: "https://covers.openlibrary.org/b/id/8235638-L.jpg",
  },
];

export const genres: string[] = [
  "Fiction",
  "Fantasy",
  "Mystery",
  "Science Fiction",
  "Non-Fiction",
  "Biography",
  "Historical",
];
